---

- name: Create the node-exporter group
  group:
    name: node-exporter
    system: true

- name: Create the node-exporter user
  user:
    name: node-exporter
    group: node-exporter
    system: yes
    createhome: no

- name: install universe repo
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present

- name: install node-exporter
  apt:
    name: prometheus-node-exporter
    state: latest
    update_cache: yes
  notify:
    - restart node exporter

- name: Start and enable the node-exporter service
  service:
    name: prometheus-node-exporter
    state: started
    enabled: true
