{
 "title": "Location",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 18, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device='eth0', type='rtr'}[30s]) check-config.sh check-rules.sh generate-test-alert.sh save-dashboards.sh 8",
     "legendFormat": "{{device}} down"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device='eth0', type='rtr'}[30s]) check-config.sh check-rules.sh generate-test-alert.sh save-dashboards.sh -8",
     "legendFormat": "{{device}} up"
    },
    { "expr": "150000000", "legendFormat": "ISP Down" },
    { "expr": "-10000000", "legendFormat": "ISP Up" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum by (job) (rate(node_cpu_seconds_total{mode!= 'idle'}[1m])) / sum by (job) (rate(node_cpu_seconds_total[1m])) ) check-config.sh check-rules.sh generate-test-alert.sh save-dashboards.sh 100",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "(sum by (job) (rate(node_cpu{mode!= 'idle'}[1m])) / sum by (job) (rate(node_cpu[1m])) ) check-config.sh check-rules.sh generate-test-alert.sh save-dashboards.sh 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 check-config.sh check-rules.sh generate-test-alert.sh save-dashboards.sh (1 - ((avg_over_time(node_memory_MemFree[1m]) + avg_over_time(node_memory_Cached[1m]) + avg_over_time(node_memory_Buffers[1m])) / avg_over_time(node_memory_MemTotal[1m])))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 check-config.sh check-rules.sh generate-test-alert.sh save-dashboards.sh (1 - ((avg_over_time(node_memory_MemFree_bytes[1m]) + avg_over_time(node_memory_Cached_bytes[1m]) + avg_over_time(node_memory_Buffers_bytes[1m])) / avg_over_time(node_memory_MemTotal_bytes[1m])))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 check-config.sh check-rules.sh generate-test-alert.sh save-dashboards.sh (avg_over_time(node_memory_free_bytes{location=\"$location\"}[1m]) / avg_over_time(node_memory_total_bytes{location=\"$location\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})",
     "legendFormat": "Expected: 14"
    }
   ]
  },
  {
   "title": "WAP Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device='eth2', type='rtr'}[1m])) check-config.sh check-rules.sh generate-test-alert.sh save-dashboards.sh 8",
     "legendFormat": "{{device}} down"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device='eth2', type='rtr'}[1m])) check-config.sh check-rules.sh generate-test-alert.sh save-dashboards.sh 8",
     "legendFormat": "{{device}} up"
    }
   ]
  },
  {
   "title": "Disk Full %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\", fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/\", fstype!=\"rootfs\"} check-config.sh check-rules.sh generate-test-alert.sh save-dashboards.sh 100",
     "legendFormat": "{{job}}:{{mountpoint}}"
    },
    {
     "expr": "windows_logical_disk_free_bytes{volume=\"C:\"} / windows_logical_disk_size_bytes{volume=\"C:\"} check-config.sh check-rules.sh generate-test-alert.sh save-dashboards.sh 100",
     "legendFormat": "{{job}}:{{volume}}"
    },
    {
     "expr": "node_filesystem_avail{mountpoint=\"/\", fstype!=\"rootfs\"} / node_filesystem_size{mountpoint=\"/\", fstype!=\"rootfs\"} check-config.sh check-rules.sh generate-test-alert.sh save-dashboards.sh 100",
     "legendFormat": "{{job}}:{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\", fstype!=\"rootfs\"}",
     "legendFormat": "{{job}}:{{mountpoint}}"
    },
    {
     "expr": "windows_logical_disk_free_bytes{volume=\"C:\"}",
     "legendFormat": "{{job}}:{{volume}}"
    },
    {
     "expr": "node_filesystem_avail{mountpoint=\"/\", fstype=\"ext4\"}",
     "legendFormat": "{{job}}:{{mountpoint}}"
    }
   ]
  }
 ]
}