{
 "title": "Location",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 18, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{location=\"jmd\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!='lo', type='rtr'}[1m]))",
     "legendFormat": "{{device}} down"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!='lo', type='rtr'}[1m])) * -1",
     "legendFormat": "{{device}} up"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum by (job) (rate(node_cpu_seconds_total{mode!= 'idle'}[1m])) / sum by (job) (rate(node_cpu_seconds_total[1m])) ) * 100",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "(sum by (job) (rate(node_cpu{mode!= 'idle'}[1m])) / sum by (job) (rate(node_cpu[1m])) ) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree[1m]) + avg_over_time(node_memory_Cached[1m]) + avg_over_time(node_memory_Buffers[1m])) / avg_over_time(node_memory_MemTotal[1m])))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[1m]) + avg_over_time(node_memory_Cached_bytes[1m]) + avg_over_time(node_memory_Buffers_bytes[1m])) / avg_over_time(node_memory_MemTotal_bytes[1m])))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * (avg_over_time(node_memory_free_bytes[1m]) / avg_over_time(node_memory_total_bytes[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "WAP Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device='eth2', type='rtr'}[1m]))",
     "legendFormat": "{{device}} down"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device='eth2', type='rtr'}[1m])) * -1",
     "legendFormat": "{{device}} up"
    }
   ]
  }
 ]
}