{
 "title": "Location",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" },
   { "name": "location", "query": "label_values(location)" }
  ]
 },
 "panels": [
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 16, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{location=\"$location\", type!~\"cam|bbx|dkr\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cameras",
   "type": "stat",
   "gridPos": { "h": 16, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{location=\"$location\", type=\"cam\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!='lo', type='rtr'}[1m]))",
     "legendFormat": "{{device}} down"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!='lo', type='rtr'}[1m])) * -1",
     "legendFormat": "{{device}} up"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (job) (rate(node_cpu_seconds_total{location=\"$location\", mode!= 'idle'}[1m])) / sum by (job) (rate(node_cpu_seconds_total{location=\"$location\"}[1m])) ) * 100",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "(sum by (job) (rate(node_cpu{location=\"$location\", mode!= 'idle'}[1m])) / sum by (job) (rate(node_cpu{location=\"$location\"}[1m])) ) * 100",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum by (job) (rate(windows_cpu_time_total{mode!=\"idle\"}[1m])) / sum by (job) (rate(windows_cpu_time_total[1m])) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree{location=\"$location\"}[1m]) + avg_over_time(node_memory_Cached{location=\"$location\"}[1m]) + avg_over_time(node_memory_Buffers{location=\"$location\"}[1m])) / avg_over_time(node_memory_MemTotal{location=\"$location\"}[1m])))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{location=\"$location\"}[1m]) + avg_over_time(node_memory_Cached_bytes{location=\"$location\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{location=\"$location\"}[1m])) / avg_over_time(node_memory_MemTotal_bytes{location=\"$location\"}[1m])))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 * (avg_over_time(node_memory_free_bytes{location=\"$location\"}[1m]) / avg_over_time(node_memory_total_bytes{location=\"$location\"}[1m]))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "(1 - ((avg_over_time(windows_os_virtual_memory_free_bytes[1m])) / windows_cs_physical_memory_bytes) ) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "WAP Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device='eth2', type='rtr'}[1m]))",
     "legendFormat": "{{device}} down"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device='eth2', type='rtr'}[1m])) * -1",
     "legendFormat": "{{device}} up"
    }
   ]
  },
  {
   "title": "Disk Full %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - (windows_logical_disk_free_bytes{volume=\"C:\"} / windows_logical_disk_size_bytes{volume=\"C:\"})) * 100",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "(1 - (node_filesystem_avail{mountpoint='/', fstype!='rootfs'} / node_filesystem_size{mountpoint='/', fstype!='rootfs'})) * 100",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "(1 - (node_filesystem_avail_bytes{mountpoint='/', fstype!='rootfs'} / node_filesystem_size_bytes{mountpoint='/', fstype!='rootfs'})) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{volume=\"C:\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "node_filesystem_avail{mountpoint='/', fstype!='rootfs'}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint='/', fstype!='rootfs'}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Docker Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_last_seen{name!=\"\"} > bool (time() - 300)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}