---

- name: Create the Prometheus TSDB directory
  file:
    name: "{{ prometheus_tsdb_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755

- name: Create the Prometheus configuration directory
  file:
    name: "{{ prometheus_config_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755

- name: Create the Prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_path }}/{{ prometheus_config_file }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0640
  notify: restart prometheus

- name: install alertmanager config
  template:
    src: !unsafe 'alertmanager.yml.j2'
    dest: /etc/prometheus/alertmanager.yml
  notify:
    - restart alertmanager
    - restart prometheus
